---
- name: Playbook 6 - Start OpenStack Controller Services
  hosts: controller
  user: heat-admin
  become: true
  tasks:
    - set_fact:
        bootstrap_node: false
    - name: test ping
      ping:
